services:
  app:
    image: bigjack325/exoflex:latest
    container_name: exoflex-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    ports:
      - "1338:1338"
      - "3001:3001"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    group_add:
      - dialout
      - tty
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true                  # Remove old images
      - WATCHTOWER_POLL_INTERVAL=30             # Check every 30 seconds
      - WATCHTOWER_INCLUDE_STOPPED=false         # Don't update stopped containers
      - WATCHTOWER_LABEL_ENABLE=true            # Only update containers with label
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: --label-enable  
