services:
  app:
    container_name: exoflex-app
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - linux/arm64
    image: bigjack325/exoflex:latest
    env_file:
      - .env.production
    ports:
      - "1338:1338"
      - "3001:3001"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    group_add:
      - dialout
      - tty
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_PULL_ALWAYS=true
    command: --debug