name: Black Styling

# Corrects Python code formatting using Black

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Black
        run: python -m pip install --upgrade black

      - name: Run Black
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD -- .
          black .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Black changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
