name: Ceedling CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.33

    - name: Install Ceedling
      run: gem install ceedling

    - name: Build and test with Ceedling
      run: |
        cd master/stm32/UnitTests/
        ceedling
