name: Ceedling CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Ceedling
      run: gem install ceedling

    - name: Run Unit Tests
      run: |
        cd master/stm32/UnitTests
        ceedling test:all


      
#     - name: Install Ceedling
#       uses: batov/ceedling_action@master
#       with:
#         test_directory: master/stm32/UnitTests
