name: Code Formatting

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  formatting:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Formatters
        run: |
          npm install --global prettier
          python -m pip install --upgrade black
          sudo apt-get install -y clang-format

      - name: Checkout Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD -- .

      - name: Run Prettier
        run: prettier --write .
      
      - name: Run Black
        run: black .
        
      - name: Format code with Clang-Format
        run: clang-format -i  stm32/h7a3zi-q/Manager/Src/*.c stm32/h7a3zi-q/Manager/Inc/*.h stm32/h7a3zi-q/UnitTests/test/*.c stm32/h7a3zi-q/Periph/Inc/*.h stm32/h7a3zi-q/Periph/Src/*.c
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
