name: Code Formatting

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  formatting:
    runs-on: ubuntu-latest
    
#     strategy:
#       matrix:
#         path:
#           - 'master/arduino/src'
#           - 'master/stm32/h7a3zi-q/Manager/Src'
#           - 'master/stm32/h7a3zi-q/Manager/Inc'
#           - 'master/stm32/h7a3zi-q/UnitTests/test'
#           - 'master/stm32/l432kc/Manager/Src'
#           - 'master/stm32/l432kc/Manager/Inc'
#           - 'master/stm32/l432kc/UnitTests/test'
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Formatters
        run: |
          npm install --global prettier
          python -m pip install --upgrade black
          sudo apt-get install -y clang-format
          
      - name: Clean up the working directory
        run: git reset --hard HEAD

      - name: Checkout Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD -- .

      - name: Run Prettier
        run: prettier --write .
      
      - name: Run Black
        run: black .
        
      - name: Format code with Clang-Format
        run: clang-format -i master/stm32/h7a3zi-q/Manager/Src/*.c master/stm32/h7a3zi-q/UnitTests/test/*.c master/stm32/h7a3zi-q/Manager/Inc/*.h master/stm32/l432kc/Manager/Src/*.c master/stm32/l432kc/UnitTests/test/*.c master/stm32/l432kc/Manager/Inc/*.h

#       - name: Run Clang-Format Verifier
#         uses: jidicula/clang-format-action@v4.11.0
#         with:
#           clang-format-version: '13'
#           check-path: ${{ matrix.path }}
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
