name: Code Formatting

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  formatting:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Formatters
        run: |
          npm install --global prettier
          sudo apt-get install -y clang-format

      - name: Checkout Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD -- .

      - name: Run Prettier
        run: prettier --write .
        
      - name: Format code with Clang-Format
        run: clang-format -i  stm32/h7a3zi-q/Manager/Src/*.c stm32/h7a3zi-q/Manager/Inc/*.h stm32/h7a3zi-q/Periph/Inc/*.h stm32/h7a3zi-q/Periph/Src/*.c
        # stm32/h7a3zi-q/UnitTests/test/*.c
          
      - name: Get Last Commit Message
        id: get_commit_msg
        run: |
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Format: ${{ steps.get_commit_msg.outputs.msg }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
