name: Code Formatting

# Corrects with Prettier: JavaScript, TypeScript, HTML, CSS, JSON, and YAML
#                         Black: Python

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Formatters
        run: |
          npm install --global prettier
          python -m pip install --upgrade black

      - name: Run Formatters
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD -- .
          prettier --write .
          black .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

