name: Delete Branch After Merge
on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git push --delete origin ${{ github.ref }}
          else
            echo "Cannot delete the main branch."
          fi
