name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify checkboxes
        run: |
          PR_TEMPLATE_PATH=".github/pull_request_template.md"
          CHECKMARK="[x]"

          # Check if the PR template file exists
          if [ -f "$PR_TEMPLATE_PATH" ]; then
            # Check if all checkboxes are checked
            if grep -q "$CHECKMARK" "$PR_TEMPLATE_PATH"; then
              echo "All checkboxes are checked. PR template validation successful!"
            else
              echo "ERROR: Some checkboxes are not checked in the PR template."
              exit 1
            fi
          else
            echo "ERROR: PR template file not found."
            exit 1
          fi
