name: Super-Linter CI

on:
  push:
    branches:
      - main
    paths:
      - ExoFlex-master/**

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          GITHUB_WORKSPACE: ExoFlex-master/ExoFlex-Arduino/src
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
